### PR TITLE
dlFilter v1.18

### PR DESCRIPTION
**Pull request by Sophist-UK**
Please do not merge this until I confirm it is ready.

### CODE REVIEW

**Comment by Sophist-UK** [comment]
@SanderSade Happy to have this merged and put the remaining stuff for v2 into a r1.19.

**Comment by SanderSade** [comment]
Sorry about the long delay - I've been (and will continue to be for a few months) very busy. 

I tested 1.18 a bit and found some issues:
- dlf.Ads lights up when first created
- dlf.Ads doesn't wrap the text
- I get messages in status window like:
Status Window 15
@dlF.Ads.irchighway 402
Status Window 15
#ebooks 341
#ebooks 341
#ebooks 341

- @find headers are not captured/are sent to channel:
[17/08/05 09:32:36] Private: <pondering> Search Result ? More than 25 Matches For cornwell ? Get My List Of 590,705 Files By Typing @pondering In The Channel Or Refine Your Search. Sending first 5 Results ? OmenServe v2.72 ?
[17/08/05 09:32:38] Private: <phoomphy> From list @phoomphy found 17, displaying 3:
[17/08/05 09:32:39] Private: <patiencel> From list @patiencel found 30, displaying 5:
[17/08/05 09:32:56] Private: <patiencel> From list @patienceltd found 15, displaying 0:

- UPP header line shows up for @find in a private window, too:
[17/08/05 09:33:29] <ps2> •·found 17 matches·• on my fserve: •·File Server Online·• Trigger..::/ctcp ps2 !ps::.. On server..::Books of all subjects, comics, wargames & RPGs (mostly pdf)::.. Note..::On Undernet & IRCHighWay: @ps2 for instructions or /ctcp ps2 !ps to enter. Elsewhere: @ps for instructions or /ctcp ps !ps to enter.::.. .•«UPP»•.

- closing <ps2> chat window sends "0" in status window
- instead "Double click to get a full list" in @find (which is a really good idea), perhaps this could be a rclick menu item for getting the list?

**Comment by Sophist-UK** [comment]
Still working on it – but getting close to release.

**Comment by Sophist-UK** [comment]
I will look into the issues below – some of which I am already aware of (like the status messages when changing windows which is for functionality that shows dlFilter efficiency).

I have just pushed the latest changes to Github.

**Comment by Sophist-UK** [comment]
1.. dlF.Ads lighting up – fixed in next push to Github

  2.. dlF.Ads not wrapping text – dlF.Ads is a listbox window (so you can select lines and double click to get the servers list of files) and listbox windows cannot wrap AFAIK.

  3.. Status messages are for debugging as previously noted. They are gone now.

  4.. @find headers are intentionally sent to channel if they cannot be sent to the @find window. This lists only the files and options to get a full file list from the sever (and is sorted by filename) so other messages can’t be sent there. The first example you have given should however be sent to the @find window. On reflection the others should probably be filtered rather than sent to the channel window. I just tried “@find cornwell” myself and there is more work needed to make this really good.

  5.. ps2 needs special handling – I will see what I can do about it.

  6.. As 3. but a bug in mIRC which doesn’t handle closed windows correctly.

  7.. Yes – will change get selected files to get selected list. Also need to fix popup menu to disable some options when no lines selected.
Also:

Still some bugs in the titlebar code.

Going to remove the anti-spam option for @find – because it seems normal to get messages from servers which don’t match the trigger.

**Comment by Sophist-UK** [comment]
Hmmm ... wondering whether supporting ps2 is worth the effort.

ps2 is a fserve bot which uses dcc chat windows to fserve. It is possible to automate using it from the @find window, and to track and autoaccept file requests, but it doesn’t seem worth the effort.

So, my plan is either to filter ps2 @find results out completely or to send them to channel like now. What would your preference be?

**Comment by SanderSade** [comment]
I agree, we deal with the list servers only, UPP and other such can be ignored.

Couple more things:
- file send starts should still show up in status
- SearchBot notices should not be filtered out
-* /hdel: no such table 'DLF.dccsend.retries' (line 1303, DLFilter.mrc)

**Comment by Sophist-UK** [comment]
Why do you want file send starts to show up in status?

Part of what I am trying to achieve with dlFilter is to put the messages in the right place (i.e. where the user sent the command that resulted in the file send).

**Comment by SanderSade** [comment]
I think people are used to checking if download started in status. I know I do, even when using AG/vPG.

**Comment by Sophist-UK** [comment]
Not keen on adding more new functionality, but would a window showing status of outstanding requests be useful?

**Comment by ps** [comment]
Hey guys, @ps here of error 'e'
```
 e.. ... Elsewhere: @ps for instructions or /ctcp ps !ps to enter.::.. .•«UPP»•.
```
All looks good to me.

**Comment by SanderSade** [comment]
"Not keen on adding more new functionality, but would a window showing status of outstanding requests be useful?"

I think this would be already AG/vPG territory.

**Comment by Sophist-UK** [comment]
Phew.

**Comment by SanderSade** [comment]
Results from this evening's testing from UnderNet #bookz
```
- in status, DLF.PRIV.OPSUSER Unknown command
- we need "Copy line" for Ads window in menu - to report bad results, at least
- hamsterbacke ad has "@hamsterbacke,", dlF sends the request with comma to the channel
- private window:[17/08/17 22:07:04] <hamsterbacke> Resultlimit by 5 reached. Download my list for more, by typing @hamsterbacke
- empty line in @find results with just nick: !hamsterbacke
- no other matches from hamsterbacke in there
- on list request, PM: [17/08/17 22:09:59] -hamsterbacke- Sending you my full list... (this may be because I had PM window already open)
- in status window:
6
cline 3 @dlF.@find.UnderNet 7
5
5

- after manual list request in status
[17/08/17 22:09:59] [dlFilter] Blocked: DCC Send from hamsterbacke (~hamster@46.246.85.39) because the file was not requested: D:\backup\mIRC\downloads\hamsterbacke_books_cmd.7z
[17/08/17 22:09:59] [dlFilter] If this file was requested add this nick to your DCC trusted list with /dcc trust hamsterbacke and retry your request.
Same after doing /dcc trust hamsterbacke


hamsterbacke:
[17/08/17 22:12:44] -> [hamsterbacke] VERSION
[17/08/17 22:12:45] [hamsterbacke VERSION reply] irssi v0.8.20

- This should show the nick, too:
[17/08/17 22:06:59] * •·@find·• Searching For..::*cornwell*::..
[17/08/17 22:07:01] * [%] Matches found in [/books\fiction & novels\c] Trigger..::/ctcp ps2 !ps::..
[17/08/17 22:07:04] * 1: (cornwell, Bernard - Alfred the Great, Bk 2 - Pale Horseman (2005).pdf 2.19MB)
[17/08/17 22:07:06] * 2: (cornwell, Bernard - The Grail Quest, Bk 2 - Vagabond (2002).pdf 1.51MB)
--

- [17/08/17 22:21:36] [dlFilter] Error: DLF.Socket.Update: https://raw.githubusercontent.com/SanderSade/dlFilter/master/dlFilter.version: dlFilter version missing!
That was probably you just commiting the changed dlf.version

- color uncolored fileservers functionality does not work at all
```

**Pull request merged**
